apiVersion: v1
kind: Service
metadata:
  name: couchbaseserver
spec:
  selector:
    app: couchbase
  ports:
  - port: 11210
    name: port0
    protocol: TCP
    targetPort: 11210
    nodePort: 31210
  - port: 8091
    name: port1
    protocol: TCP
    targetPort: 8091
    nodePort: 30091
  - port: 8092
    name: port2
    protocol: TCP
    targetPort: 8092
    nodePort: 30092
  - port: 8093
    name: port3
    protocol: TCP
    targetPort: 8093
    nodePort: 30093
  - port: 8094
    name: port4
    protocol: TCP
    targetPort: 8094
    nodePort: 30094
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: couchbase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchbase
  template:
    metadata:
      labels:
        app: couchbase
    spec:
      containers:
      - name: couchbase
        image: couchbase
        ports:
        - containerPort: 11210
        - containerPort: 8091
        - containerPort: 8092
        - containerPort: 8093
        - containerPort: 8094
