apiVersion: v1
kind: Service
metadata:
  name: dosbox
spec:
  selector:
    app: dosbox
  ports:
  - port: 5901
    protocol: TCP
    targetPort: 5901
    nodePort: 30901
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dosbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dosbox
  template:
    metadata:
      labels:
        app: dosbox
    spec:
      containers:
      - name: dosbox
        image: jgoerzen/dosbox
        env:
        - name: VNCPASSWORD
          value: "P@ssw0rd"
        ports:
        - containerPort: 5901
