apiVersion: v1
kind: Service
metadata:
  name: scratch3
spec:
  selector:
    app: scratch3
  ports:
  - port: 8601
    protocol: TCP
    targetPort: 8601
    nodePort: 30601
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scratch3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scratch3
  template:
    metadata:
      labels:
        app: scratch3
    spec:
      containers:
      - name: scratch3
        image: kadok0520/mit-scratch3
        ports:
        - containerPort: 8601
