apiVersion: v1
kind: Service
metadata:
  name: vncserver
spec:
  selector:
    app: vncserver
  ports:
  - port: 5901
    protocol: TCP
    targetPort: 5901
    nodePort: 30901
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vncserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vncserver
  template:
    metadata:
      labels:
        app: vncserver
    spec:
      containers:
      - name: vncserver
        image: vncserver/lubuntu
        ports:
        - containerPort: 5901
