apiVersion: v1
kind: Service
metadata:
  name: wasliberty
spec:
  selector:
    app: wasliberty
  ports:
  - port: 9080
    name: port0
    protocol: TCP
    targetPort: 9080
    nodePort: 30080
  - port: 9443
    name: port2
    protocol: TCP
    targetPort: 9443
    nodePort: 30443
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasliberty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasliberty
  template:
    metadata:
      labels:
        app: wasliberty
    spec:
      containers:
      - name: wasliberty
        image: websphere-liberty
        ports:
        - containerPort: 9080
        - containerPort: 9443
