apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  selector:
    app: wordpress
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30083
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress
        env:
        - name: WORDPRESS_DB_HOST
          value: "169.51.204.190:30306"
        - name: WORDPRESS_DB_USER
          value: "user1"
        - name: WORDPRESS_DB_PASSWORD
          value: "password1"
        - name: WORDPRESS_DB_NAME
          value: "mydb"
        ports:
        - containerPort: 80
