apiVersion: v1
kind: Service
metadata:
  name: db2
spec:
  selector:
    app: db2
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
    nodePort: 30500
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
      labels:
        app: db2
    spec:
      containers:
      - name: db2
        image: ibmcom/db2
        securityContext:
          privileged: true
        env:
        - name: LICENSE
          value: "accept"
        - name: DB2INST1_PASSWORD
          value: "db2inst1"
        - name: DBNAME
          value: "mydb"
        - name: SAMPLEDB
          value: "true"
        ports:
        - containerPort: 50000
